name: aaftf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - samtools>=1.23,<2
  - biopython
  - bwa
  - minimap2
  - pilon
  - blast
  - diamond
  - bowtie2
  - sourmash
  - trimmomatic
  - megahit
  - unicycler
  - spades
  - fastp
  - flye
  - racon
  - fastqc
  - hifiasm
  - kraken2
  - novoplasty
  - ncbi-fcs-gx
  - mosdepth
  - matplotlib
  - bbmap>=39.80,<40
  - masurca>=4.1.4,<5
  - pytest>=7.0
  - pip
  - pip:
    - aaftf
