name: AAFTF
channels:
  - bioconda
  - conda-forge
dependencies:
  - biopython
  - samtools
  - bwa
  - minimap2
  - pilon
  - blast
  - diamond
  - sourmash
  - bowtie2
  - trimmomatic
  - spades
  - fastp
  - novoplasty
  - bbmap
  - ncbi-fcs-gx
  - masurca
  - nextpolish
  - pip
  - pip:
    - AAFTF
