name: aaftf-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - samtools>=1.23,<2
  - biopython
  - bwa
  - minimap2
  - pilon
  - blast
  - diamond
  - sourmash
  - bowtie2
  - trimmomatic
  - spades
  - fastp
  - novoplasty
  - ncbi-fcs-gx
  - mosdepth
  - matplotlib
  - bbmap>=39.80,<40
  - masurca>=4.1.4,<5
  - pytest>=7.0
  - pip
  - pip:
    - -e .
    - pytest-cov
