[workspace]
authors = ["Jason Stajich <jasonstajich.phd@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "AAFTF"
platforms = ["linux-64"]
version = "0.6.2"

[tasks]

[dependencies]
python = "3.10.*"
samtools = ">=1.23,<2"
biopython = "*"
bwa = "*"
minimap2 = "*"
pilon = "*"
blast = "*"
diamond = "*"
sourmash = "*"
bowtie2 = "*"
trimmomatic = "*"
spades = "*"
fastp = "*"
novoplasty = "*"
ncbi-fcs-gx = "*"
mosdepth = "*"
matplotlib = "*"
pip = "*"
bbmap = ">=39.80,<40"
masurca = ">=4.1.4,<5"
pytest = ">=9.0.3,<10"
taxonkit = ">=0.20.0,<0.21"

[pypi-dependencies]
aaftf = { path = ".", editable = true}
